server:
  port: 9000
spring:
  application:
    name: rag-spring-ai
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: mistral
        options:
          top-k: 2
      embedding:
        model: mxbai-embed-large
    openai:
      image:
        enabled: false
    vectorstore:
      pgvector:
        index-type: hnsw
        dimensions: 1024
        remove-existing-vector-store-table: true
        distance-type: cosine_distance
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect