server.port=9000
spring.application.name=rag-spring-ai
spring.main.allow-bean-definition-overriding=true
spring.ai.ollama.base-url=http://156.35.95.18:11434
spring.ai.ollama.chat.model=gemma3:4b
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=gemma2:latest
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.ollama.top-k=50
spring.ai.ollama.similarity-threshold=0.0
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- Flags de activacion de mejoras del sistema RAG ---
rag.features.expansion-enabled=false
rag.features.tools-enabled=true
rag.features.validation-enabled=false
rag.features.reasoning-enabled=false
rag.features.ner-enabled=true
rag.features.metadata-enabled=true

# --- Flags de cache y optimizacion ---
# rag.features.cache-enabled=false
# rag.features.cache-documents-enabled=false
# rag.features.cache-metadata-enabled=false
# rag.features.cache-ner-enabled=false
# rag.features.parallel-processing-enabled=false
# rag.features.adaptive-prompts-enabled=false