server.port=9000
spring.application.name=rag-spring-ai
spring.main.allow-bean-definition-overriding=true
spring.ai.ollama.base-url=http://156.35.95.18:11434
spring.ai.ollama.chat.model=gemma3:4b
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=gemma2:latest
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.ollama.top-k=10
spring.ai.ollama.similarity-threshold=0.5
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- Flags de activación de mejoras del sistema RAG ---
rag.features.expansion-enabled=false
rag.features.tools-enabled=true
rag.features.validation-enabled=false
rag.features.reasoning-enabled=false
rag.features.ner-enabled=true
rag.features.metadata-enabled=true
