server:
  port: 9000
spring:
  application:
    name: rag-spring-ai
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma2:latest
        options:
          top-k: 2
      embedding:
        model: mxbai-embed-large
    vectorstore:
      pgvector:
        index-type: hnsw
        dimensions: 1024
        remove-existing-vector-store-table: true
        distance-type: cosine_distance
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

document:
  upload:
    allowed-types:
      - application/pdf
      - text/plain
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - application/vnd.ms-excel