#!/usr/bin/env bash
# Shared defaults for P0 Playwright CI stack (sourced by start/wait/stop scripts).
# HTTPS reverse-proxy on :8444 matches webapp/scripts/e2e-bases.mjs and lab-demo conventions.

export E2E_STACK_MODE="${E2E_STACK_MODE:-https-proxy}"
export REVERSE_PROXY_DEV_HTTP_PORT="${REVERSE_PROXY_DEV_HTTP_PORT:-8080}"
export REVERSE_PROXY_DEV_HTTPS_PORT="${REVERSE_PROXY_DEV_HTTPS_PORT:-8444}"
export REVERSE_PROXY_ENFORCE_HTTPS="${REVERSE_PROXY_ENFORCE_HTTPS:-0}"

export PLAYWRIGHT_BASE_URL="${PLAYWRIGHT_BASE_URL:-https://127.0.0.1:${REVERSE_PROXY_DEV_HTTPS_PORT}}"
export E2E_PUBLIC_BASE_URL="${E2E_PUBLIC_BASE_URL:-${PLAYWRIGHT_BASE_URL}}"
export E2E_PRODUCT_URL="${E2E_PRODUCT_URL:-${PLAYWRIGHT_BASE_URL}}"
export API_BASE_URL="${API_BASE_URL:-${E2E_PRODUCT_URL}}"
export E2E_BACKEND_HEALTH_URL="${E2E_BACKEND_HEALTH_URL:-${PLAYWRIGHT_BASE_URL}}"
export E2E_WEB_HEALTH_URL="${E2E_WEB_HEALTH_URL:-${PLAYWRIGHT_BASE_URL}}"

export PLAYWRIGHT_SKIP_WEBSERVER="${PLAYWRIGHT_SKIP_WEBSERVER:-1}"
export PLAYWRIGHT_IGNORE_HTTPS_ERRORS="${PLAYWRIGHT_IGNORE_HTTPS_ERRORS:-1}"
export NODE_TLS_REJECT_UNAUTHORIZED="${NODE_TLS_REJECT_UNAUTHORIZED:-0}"
export E2E_ALLOW_INSECURE_COOKIES="${E2E_ALLOW_INSECURE_COOKIES:-true}"

export E2E_SEED_EMAIL="${E2E_SEED_EMAIL:-dev@local.test}"
export E2E_SEED_PASSWORD="${E2E_SEED_PASSWORD:-dev}"
export E2E_ADMIN_EMAIL="${E2E_ADMIN_EMAIL:-admin@e2e.local}"
export E2E_ADMIN_PASSWORD="${E2E_ADMIN_PASSWORD:-e2e}"
export E2E_ADMIN_ENABLED="${E2E_ADMIN_ENABLED:-1}"

export PLAYWRIGHT_RETRIES="${PLAYWRIGHT_RETRIES:-1}"
export PLAYWRIGHT_WORKERS="${PLAYWRIGHT_WORKERS:-1}"
export PLAYWRIGHT_MAX_FAILURES="${PLAYWRIGHT_MAX_FAILURES:-1}"
export PLAYWRIGHT_TEST_TIMEOUT_MS="${PLAYWRIGHT_TEST_TIMEOUT_MS:-360000}"
export PLAYWRIGHT_EXPECT_TIMEOUT_MS="${PLAYWRIGHT_EXPECT_TIMEOUT_MS:-15000}"
export PLAYWRIGHT_TRACE="${PLAYWRIGHT_TRACE:-retain-on-failure}"

export E2E_STACK_PREFLIGHT_MAX_MS="${E2E_STACK_PREFLIGHT_MAX_MS:-300000}"
export E2E_STACK_PREFLIGHT_REQUEST_MS="${E2E_STACK_PREFLIGHT_REQUEST_MS:-30000}"
export DEV_SMOKE_TIMEOUT_SECONDS="${DEV_SMOKE_TIMEOUT_SECONDS:-300}"
export DEV_SMOKE_BASE_URL="${DEV_SMOKE_BASE_URL:-${PLAYWRIGHT_BASE_URL}}"
export DEV_SMOKE_HEALTH_BASE="${DEV_SMOKE_HEALTH_BASE:-${E2E_BACKEND_HEALTH_URL}}"

export RAG_DEMO_BASE_URL="${RAG_DEMO_BASE_URL:-${PLAYWRIGHT_BASE_URL}}"
