package com.uniovi.rag.domain.runtime.tracereplay;

/**
 * Closed terminal outcome for one replay attempt (P18). Exactly one per request.
 */
public enum RuntimeTraceReplayOutcome {
    NOT_ATTEMPTED,
    UNSUPPORTED_MISSING_LINKAGE,
    UNSUPPORTED_CLARIFICATION_DEPENDENT,
    UNSUPPORTED_JUDGE_AFFECTED,
    UNSUPPORTED_ROUTE_FAMILY,
    UNSUPPORTED_MISSING_KNOWLEDGE_BINDING,
    UNSUPPORTED_MISSING_TOOL_BINDING,
    UNSUPPORTED_MISSING_WORKFLOW_NAME,
    UNSUPPORTED_MISSING_RESOLVED_CONFIG_SNAPSHOT_ID,
    UNSUPPORTED_TRACE_SCHEMA_VERSION,
    REPLAY_SUCCEEDED,
    REPLAY_FAILED_SAFE
}
