import { vi } from "vitest";
import type { ChatToolbarApi } from "@/features/chat/store/chat-toolbar.store";
import { mockChatRuntimeState } from "@/test-utils/chat-runtime-state-mock";

/** Minimal valid {@link ChatToolbarApi} for chat configuration panel tests. */
export function mockChatToolbarApi(overrides: Partial<ChatToolbarApi> = {}): ChatToolbarApi {
  return {
    projectId: "p1",
    conversationId: "c1",
    openDeleteForActiveConversation: vi.fn(),
    openMoveDialog: vi.fn(),
    openDocumentsSheet: vi.fn(),
    onAddDocuments: vi.fn(),
    llmModelChoice: "",
    setLlmModelChoice: vi.fn(),
    classifierModelChoice: "",
    setClassifierModelChoice: vi.fn(),
    selectableLlmModels: [],
    selectableLlmModelsLoading: false,
    selectableLlmModelsEffectiveProvider: "OPENAI_COMPATIBLE",
    modelsError: false,
    modelsErrorMessage: "",
    presetSelectValue: "",
    onPresetChange: vi.fn(),
    presets: [],
    presetsError: false,
    presetsLoading: false,
    projectCompatiblePresets: null,
    compatibleProductPresets: [],
    compatibleExperimentalPresets: [],
    experimentalPresets: [],
    experimentalPresetsLoading: false,
    experimentalPresetsError: false,
    presetSelectDisabled: false,
    syntheticPresetOptionNeeded: false,
    presetLabelOpts: {
      systemSuffix: " (system)",
      recommendedDefault: "Recommended default",
      defaultConfiguration: "Default configuration",
    },
    limitDocs: false,
    onLimitDocsChange: vi.fn(),
    limitDocsDisabled: false,
    limitDocsToggleNotice: null,
    patchConvPending: false,
    uploadPending: false,
    uploadError: null,
    uploadNotice: null,
    documents: [],
    runtimeOverride: {},
    saveRuntimeOverride: vi.fn(),
    clearRuntimeOverride: vi.fn(),
    runtimeState: mockChatRuntimeState(),
    runtimeStateLoading: false,
    runtimeStateError: null,
    refreshRuntimeState: vi.fn(),
    ...overrides,
  };
}
