#!/bin/sh
set -eu

export BACKEND_HOST="${BACKEND_HOST:-backend}"
export WEBAPP_HOST="${WEBAPP_HOST:-webapp}"
export BACKEND_INTERNAL_PORT="${BACKEND_INTERNAL_PORT:-9000}"
export WEBAPP_INTERNAL_PORT="${WEBAPP_INTERNAL_PORT:-3000}"
export TLS_CERT_DIR="${TLS_CERT_DIR:-/etc/nginx/certs}"
export TLS_CERT_PATH="${TLS_CERT_PATH:-${TLS_CERT_DIR}/tls.crt}"
export TLS_KEY_PATH="${TLS_KEY_PATH:-${TLS_CERT_DIR}/tls.key}"
export OPENSSL_CONFIG="${OPENSSL_CONFIG:-/etc/nginx/openssl-san.cnf}"
export TLS_CERT_DAYS="${TLS_CERT_DAYS:-365}"
export REVERSE_PROXY_SERVER_NAME="${REVERSE_PROXY_SERVER_NAME:-localhost}"
export REVERSE_PROXY_ENFORCE_HTTPS="${REVERSE_PROXY_ENFORCE_HTTPS:-0}"
export REVERSE_PROXY_HTTPS_PORT_SUFFIX="${REVERSE_PROXY_HTTPS_PORT_SUFFIX:-}"

if [ -n "${REVERSE_PROXY_HTTPS_PORT_SUFFIX}" ] && [ "${REVERSE_PROXY_HTTPS_PORT_SUFFIX#*:}" = "${REVERSE_PROXY_HTTPS_PORT_SUFFIX}" ]; then
  REVERSE_PROXY_HTTPS_PORT_SUFFIX=":${REVERSE_PROXY_HTTPS_PORT_SUFFIX}"
  export REVERSE_PROXY_HTTPS_PORT_SUFFIX
fi
export API_PROXY_CONNECT_TIMEOUT="${API_PROXY_CONNECT_TIMEOUT:-10s}"
export API_PROXY_SEND_TIMEOUT="${API_PROXY_SEND_TIMEOUT:-180s}"
export API_PROXY_READ_TIMEOUT="${API_PROXY_READ_TIMEOUT:-180s}"
export WEB_PROXY_CONNECT_TIMEOUT="${WEB_PROXY_CONNECT_TIMEOUT:-10s}"
export WEB_PROXY_SEND_TIMEOUT="${WEB_PROXY_SEND_TIMEOUT:-180s}"
export WEB_PROXY_READ_TIMEOUT="${WEB_PROXY_READ_TIMEOUT:-180s}"
export RAG_API_PRODUCT_BASE_PATH="${RAG_API_PRODUCT_BASE_PATH:-/api/v5}"
export API_CLIENT_MAX_BODY_SIZE="${API_CLIENT_MAX_BODY_SIZE:-50m}"
export WEB_CLIENT_MAX_BODY_SIZE="${WEB_CLIENT_MAX_BODY_SIZE:-20m}"
export CONTENT_SECURITY_POLICY="${CONTENT_SECURITY_POLICY:-default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https: http: ws: wss:}"

if ! /generate-self-signed-cert.sh; then
  echo "TLS certificate generation failed." >&2
  exit 1
fi

envsubst '$BACKEND_HOST $BACKEND_INTERNAL_PORT $WEBAPP_HOST $WEBAPP_INTERNAL_PORT $TLS_CERT_PATH $TLS_KEY_PATH $REVERSE_PROXY_SERVER_NAME $REVERSE_PROXY_ENFORCE_HTTPS $REVERSE_PROXY_HTTPS_PORT_SUFFIX $API_PROXY_CONNECT_TIMEOUT $API_PROXY_SEND_TIMEOUT $API_PROXY_READ_TIMEOUT $WEB_PROXY_CONNECT_TIMEOUT $WEB_PROXY_SEND_TIMEOUT $WEB_PROXY_READ_TIMEOUT $RAG_API_PRODUCT_BASE_PATH $API_CLIENT_MAX_BODY_SIZE $WEB_CLIENT_MAX_BODY_SIZE $CONTENT_SECURITY_POLICY' \
  < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
