package com.uniovi.rag.interfaces.rest.admin;

import com.uniovi.rag.infrastructure.persistence.MailOutboxRepository;
import com.uniovi.rag.infrastructure.persistence.jpa.MailOutboxEntity;
import com.uniovi.rag.testsupport.webmvc.RagWebMvcTestApplication;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Sort;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(controllers = AdminMailOutboxController.class)
@ContextConfiguration(classes = RagWebMvcTestApplication.class)
@AutoConfigureMockMvc(addFilters = false)
@Import(AdminMailOutboxController.class)
@ActiveProfiles("dev")
@TestPropertySource(properties = "rag.api.product-base-path=/api/v5")
class AdminMailOutboxControllerWebMvcTest {

    private static final String ADMIN_MAIL_OUTBOX = "/api/v5/admin/mail-outbox";

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private MailOutboxRepository mailOutboxRepository;

    @Test
    void list_returnsMappedEntriesSortedNewestFirst_withDefaultLimit() throws Exception {
        MailOutboxEntity first = outboxEntity("a@x.com", Instant.parse("2025-01-03T00:00:00Z"));
        MailOutboxEntity second = outboxEntity("b@x.com", Instant.parse("2025-01-02T00:00:00Z"));
        when(mailOutboxRepository.findAll(any(Sort.class))).thenReturn(List.of(first, second));

        mockMvc.perform(get(ADMIN_MAIL_OUTBOX))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].recipient").value("a@x.com"))
                .andExpect(jsonPath("$[1].recipient").value("b@x.com"));

        verify(mailOutboxRepository).findAll(Sort.by(Sort.Direction.DESC, "createdAt"));
    }

    @Test
    void list_respectsLimitParameter() throws Exception {
        List<MailOutboxEntity> many = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            many.add(outboxEntity("u" + i + "@x.com", Instant.parse("2025-01-0" + (i + 1) + "T00:00:00Z")));
        }
        when(mailOutboxRepository.findAll(any(Sort.class))).thenReturn(many);

        mockMvc.perform(get("/api/v5/admin/mail-outbox").param("limit", "2"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2));
    }

    @Test
    void list_clampsLimitBelowOneToOne() throws Exception {
        MailOutboxEntity a = outboxEntity("only@x.com", Instant.now());
        MailOutboxEntity b = outboxEntity("second@x.com", Instant.now());
        when(mailOutboxRepository.findAll(any(Sort.class))).thenReturn(List.of(a, b));

        mockMvc.perform(get("/api/v5/admin/mail-outbox").param("limit", "0"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(1));
    }

    private static MailOutboxEntity outboxEntity(String recipient, Instant createdAt) {
        MailOutboxEntity e = new MailOutboxEntity();
        e.setCreatedAt(createdAt);
        e.setPurpose("EMAIL_CONFIRMATION");
        e.setRecipient(recipient);
        e.setSubject("s");
        e.setBodyText("body");
        // id left generated by DB in production; for mapping tests callers may set id manually when needed
        return e;
    }
}
